### ISSUE TITLE
In Mac Thunderbird 38.5.1, it used to be possible to send full headers in forwarded messages

### ISSUE THREAD

**Issue by jeffbfx** [jmozmoz/compactheader#1]
Before I moved to Thunderbird 38.5.1 (Macintosh), with View->Headers->All set to "All",
forwarding email produced full headers in the forwarded message. 

I've used CompactHeader for several years and full headers in forwarded messages was the behavior I came to expect when View->Headers->All was set to "All"

I am currently using CompactHeader 2.1.0 and have used it successfully in conjunction with the ToggleHeaders 1.0 add-on.  Before sending this message, I disabled ToggleHeaders so as to verify
the behavior reported here.

If you have time to fix this behavior, I would be very appreciative. Thank you.

jeff

**Comment by jmozmoz** [comment]
To really include the full header in a replied message you have to choose (before you start the reply) "All" in View->Headers. At least this is what I have to do using Windows.

I should have behaved this way all the time.

**Comment by jeffbfx** [comment]
Yes, the procedure you describe is the exact procedure I followed for several 
years to this day.  After more testing
of my Mac version (on 10.6.8), it seems that someone has changed this long-time 
behavior of T-bird itself.

I did file a bug on bugzilla.

(sigh) yet another T-bird unwanted regression...not ready to give up on T-bird 
quite yet but the day is coming.

Thank you,

## Jeff

Jeff Bloomfield
jeffb@lmi.net
