### ISSUE TITLE
JavaScript error: chrome://compactheader/content/compactHeaderOverlay.js, line 899: TypeError: digits is null

### ISSUE THREAD

**Issue by bentolor** [jmozmoz/compactheader#38]
Thank you @jmozmoz for this helpful addon.

On skimming through my `.xsession-errors.log` I saw, that the plugin spills a lot of these error messages:

```
JavaScript error: chrome://compactheader/content/compactHeaderOverlay.js, line 899: TypeError: digits is null
JavaScript error: chrome://compactheader/content/compactHeaderOverlay.js, line 899: TypeError: digits is null
JavaScript error: chrome://compactheader/content/compactHeaderOverlay.js, line 899: TypeError: digits is null
JavaScript error: chrome://compactheader/content/compactHeaderOverlay.js, line 899: TypeError: digits is null
```

I assume this should be a trivial fix/issue. I'm using 2.1.6

**Comment by jmozmoz** [comment]
Do use Linux? Which version of Thunderbird?

Have you enabled the option "Darken header if message pane has focus"? If yes, does the error message go away if you disable it?

**Comment by bentolor** [comment]
I'm on Thunderbird 6.4.0 on Linux Mint 19.1 Cinnamon.

I've enabled that option, but actually wonder what it is supposed to to. Probably enabled it because I'm using a dark theme. 

Error seems to occur after enabling this box and then clicking into the message area. I disabled it so I'm happy for now. Thanks-
