### ISSUE TITLE
http://compactheader.mozdev.org/ down?

### ISSUE THREAD

**Issue by blueyed** [jmozmoz/compactheader#39]
http://compactheader.mozdev.org/ shows only:

> MDB2 Error: unknown error 

Likely more a problem of mozdev.org probably, but wanted to report it still.

**Comment by netjeff** [comment]
Down for me, too.

**Comment by jmozmoz** [comment]
It looks like the whole site (mozdev.org) has massive problems. I think, there is no need, to use that site anymore. The source code is hosted here (on github) and new version are distributed either over addons.thunderbird.net or also here.
