### ISSUE TITLE
TB 68: Error processing legacy: An unexpected property was found in the WebExtension manifest.

### ISSUE THREAD

**Issue by blueyed** [jmozmoz/compactheader#40]
With Thunderbird 68.0 the extension does not work anymore.
When disabling and re-enabling it the following is shown in the error console:

> 1568023319394	addons.webextension.{58D4392A-842E-11DE-B51A-C7B855D89593}	WARN	Loading extension '{58D4392A-842E-11DE-B51A-C7B855D89593}': Reading manifest: Error processing legacy: An unexpected property was found in the WebExtension manifest.

I've seen the reference to https://github.com/jmozmoz/compactheader/releases in the description, but am using 3.0.0beta3 already (it says it was updated today).

The extension itself is not considered to require an update though (like others).

**Comment by blueyed** [comment]
> The extension itself is not considered to require an update though (like others).

JFI: but when downgrading Thunderbird it now says to not be compatible anymore..

**Comment by blueyed** [comment]
JFI: trying to install 2.2.0beta5 (via https://github.com/jmozmoz/compactheader/releases/tag/2.2.0beta5) says that it would be corrupt (with TB 60.8.0)

**Comment by jmozmoz** [comment]
For Thunderbird 68 you need the version 3.0.0beta3: The easiest way would be to uninstall the former version, you had installed, restart Thunderbird and then install it from the addon page within Thunderbird (search for it and then click install). You could also download it from addons.thunderbird.net: 
https://addons.thunderbird.net/thunderbird/downloads/latest/compactheader/addon-13564-latest.xpi

For Thunderbird 60 you need the last version: https://addons.thunderbird.net/en-US/thunderbird/addon/compactheader/versions/2.1.6
You can find it on the version page: https://addons.thunderbird.net/en-US/thunderbird/addon/compactheader/versions/

**Comment by blueyed** [comment]
It works for me now..

I had 3.0.0beta3 already, and still have it - not sure what has changed?!

Last Updated is still "September 9, 2019".
I've upgraded TB initially on 2019-09-06 12:33 to 68, but not restarted it then for a while.

Closing, since it is resolved (for unknown reasons).
Thanks!
